[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
exo_core = "CdamAXn5fCros3MktPxmbQKXtxd34XHATTLmh9jkn7DT"
exo_hooks = "F5CzTZpDch5gUc5FgTPPRJ8mRKgrMVzJmcPfTzTugCeK"

[programs.localnet]
exo_core = "AhG24crsnAa1HoF31U2BLtM3uQuhuRCytkbtSK8CpXjZ"
exo_hooks = "C1iSwHyPWRR48pxbiztvQ6wt92mB7WfebgpEBdTv78kw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/nate/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
